#!/bin/bash

echo "📊 APPSHEET INTEGRATION SETUP GUIDE"
echo "==================================="
echo ""

echo "📋 APPSHEET INTEGRATION OVERVIEW:"
echo "================================="
echo "AppSheet enables non-technical admin management of:"
echo "🏢 Coordination Points (locations, contacts, service areas)"
echo "💰 Pricing Structure (rates, discounts, distance fees)"
echo "📊 Booking Management (external business workflows)"
echo ""

echo "🔧 REQUIRED GITHUB SECRETS:"
echo "=========================="
echo "1. 🔑 APPSHEET_API_KEY - Your AppSheet API access key"
echo "2. 📱 APPSHEET_APP_ID - Your specific app identifier"
echo ""

echo "📥 HOW TO GET APPSHEET CREDENTIALS:"
echo "=================================="
echo "1. 🌐 Go to: https://www.appsheet.com/"
echo "2. 📱 Create/access your Clean Departure management app"
echo "3. ⚙️ Go to App Settings → Security"
echo "4. 🔑 Generate API key if not already done"
echo "5. 📋 Copy the API key and App ID"
echo ""

echo "🏗️ APPSHEET APP STRUCTURE NEEDED:"
echo "================================="
echo "Your AppSheet app should have these tables:"
echo ""
echo "📊 Table 1: CoordinationPoints"
echo "  - name (Text)"
echo "  - address (LongText)"
echo "  - city (Text)"
echo "  - state (Text)"
echo "  - phone (Phone)"
echo "  - email (Email)"
echo "  - active (Yes/No)"
echo "  - latitude (Decimal)"
echo "  - longitude (Decimal)"
echo "  - serviceRadius (Number)"
echo ""
echo "💰 Table 2: Pricing"
echo "  - service_id (Text)"
echo "  - service_name (Text)"
echo "  - price_per_sqft (Decimal)"
echo "  - weekly_discount (Percent)"
echo "  - monthly_discount (Percent)"
echo "  - distance_fee_per_mile (Decimal)"
echo "  - free_distance_miles (Number)"
echo ""
echo "📅 Table 3: Bookings (Optional)"
echo "  - booking_id (Text)"
echo "  - customer_email (Email)"
echo "  - service_type (Text)"
echo "  - square_feet (Number)"
echo "  - total_price (Price)"
echo "  - booking_date (Date)"
echo "  - status (Enum: pending, confirmed, completed)"
echo ""

echo "🔧 HOW TO ADD SECRETS TO GITHUB:"
echo "================================"
echo "1. 🌐 Go to: https://github.com/Tazaai/cleanpro-site/settings/secrets/actions"
echo "2. ➕ Click 'New repository secret'"
echo "3. 📝 Name: APPSHEET_API_KEY"
echo "4. 📋 Value: [Your AppSheet API key]"
echo "5. 💾 Click 'Add secret'"
echo "6. 🔁 Repeat for APPSHEET_APP_ID"
echo ""

echo "🧪 TEST APPSHEET INTEGRATION:"
echo "============================="
echo "After adding secrets, test with:"
echo "curl -s 'https://cleanpro-backend-2a5pka5baa-ew.a.run.app/api/appsheet/config'"
echo ""
echo "Expected response:"
echo "{"
echo '  "ok": true,'
echo '  "configured": true,'
echo '  "hasApiKey": true,'
echo '  "hasAppId": true'
echo "}"
echo ""

echo "🔗 APPSHEET API ENDPOINTS:"
echo "========================="
echo "Once configured, these endpoints will be available:"
echo "📊 GET  /api/appsheet/config - Check configuration"
echo "🧪 POST /api/appsheet/test - Test connection"
echo "🔄 POST /api/appsheet/sync/coordination-points - Sync coordination points"
echo "💰 POST /api/appsheet/sync/pricing - Sync pricing data"
echo "📊 POST /api/appsheet/sync/all - Sync all data"
echo "📅 POST /api/appsheet/push/booking/:id - Push booking to AppSheet"
echo ""

echo "🚀 DEPLOYMENT SEQUENCE:"
echo "======================"
echo "1. 🔥 Fix Firebase connection first"
echo "2. 📊 Add AppSheet secrets to GitHub"
echo "3. 🚀 Deploy updated backend"
echo "4. 🧪 Test both Firebase and AppSheet connectivity"
echo "5. 🔄 Enable real two-way data sync"
echo ""

echo "⚠️ IMPORTANT NOTES:"
echo "=================="
echo "✅ AppSheet integration requires Firebase to be working first"
echo "✅ Data will sync bidirectionally (AppSheet ↔ Firestore)"
echo "✅ Admin users can manage business data through AppSheet UI"
echo "❌ Don't configure AppSheet until Firebase connection is fixed"